#!/bin/sh

echo $DB_HOST:$DB_PORT:$DB_NAME:$POSTGRES_USER:$POSTGRES_PASSWORD > ~/.pgpass
chmod 600 ~/.pgpass

psql -U $POSTGRES_USER -c "CREATE USER $DB_USER PASSWORD '$DB_PASSWORD'"
psql -U $POSTGRES_USER -c "CREATE DATABASE $DB_NAME OWNER $DB_USER"
psql -U $POSTGRES_USER -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER"
